### ISSUE TITLE
OrangeFS kernel module does not build on Fedora 22 (4.1.6-200.fc22)

### ISSUE THREAD

**Issue by martinbrandenburg** [waltligon/orangefs#65]
Imported from Trac

ID: 66
Type: defect
Time: 1441238584
Change time: 1447339384
Component: Kernel module
Severity: None
Priority: major
Owner: hubcap
Reporter: jburto2
Cc: 
Version: latest
Milestone: 
Status: closed
Resolution: fixed
Summary: OrangeFS kernel module does not build on Fedora 22 (4.1.6-200.fc22)
Keywords: 

OrangeFS kernel module does not build on Fedora 22 (4.1.6-200.fc22)

DEBUG:root:---------------------------------------------------
DEBUG:root:Command: /usr/bin/ssh -i /home/ubuntu/cuer1/buildbot2.pem fedora@130.127.194.70 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o BatchMode=yes "cd /home/fedora/trunk; make kmod"
DEBUG:root:RC: 2
DEBUG:root:STDOUT:   CC [M]  /home/fedora/trunk/src/kernel/linux-2.6/pvfs2-utils.o
  CC [M]  /home/fedora/trunk/src/kernel/linux-2.6/devpvfs2-req.o
scripts/Makefile.build:258: recipe for target '/home/fedora/trunk/src/kernel/linux-2.6/devpvfs2-req.o' failed
Makefile:1388: recipe for target '_module_/home/fedora/trunk/src/kernel/linux-2.6' failed
Makefile:99: recipe for target 'default' failed
Makefile:860: recipe for target 'just_kmod' failed

DEBUG:root:STDERR: Warning: Permanently added '130.127.194.70' (ECDSA) to the list of known hosts.
/home/fedora/trunk/src/kernel/linux-2.6/devpvfs2-req.c:1168:5: error: unknown field ‘aio_write’ specified in initializer
     .aio_write = pvfs2_devreq_aio_write,
     ^
/home/fedora/trunk/src/kernel/linux-2.6/devpvfs2-req.c:1168:18: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     .aio_write = pvfs2_devreq_aio_write,
                  ^
/home/fedora/trunk/src/kernel/linux-2.6/devpvfs2-req.c:1168:18: note: (near initialization for ‘pvfs2_devreq_file_operations.write’)
make[3]: *** [/home/fedora/trunk/src/kernel/linux-2.6/devpvfs2-req.o] Error 1
make[2]: *** [_module_/home/fedora/trunk/src/kernel/linux-2.6] Error 2
make[1]: *** [default] Error 2
make: *** [just_kmod] Error 2

ERROR:root:Build (make) of of OrangeFS-kmod at /home/fedora/trunk Failed!
None
Ticket change
Time: 1447339384
Author: hubcap
Field: status

closed

Ticket change
Time: 1447339384
Author: hubcap
Field: resolution

fixed

Ticket change
Time: 1447339384
Author: hubcap
Field: comment

https://www.orangefs.org/svn/orangefs/branches/trunk.kernel.update/

tested on:

# cat /etc/fedora-release
Fedora release 22 (Twenty Two)
# uname -r
4.1.6-201.fc22.x86_64

          and

# cat /etc/fedora-release
Fedora release 23 (Twenty Three)
# uname -r
4.2.5-300.fc23.x86_64
