### ISSUE TITLE
Kernel module fails to build on SLES 12 (Linux 3.12.43-52.6)

### ISSUE THREAD

**Issue by martinbrandenburg** [waltligon/orangefs#61]
Imported from Trac

ID: 62
Type: defect
Time: 1436989241
Change time: 1447337984
Component: Kernel module
Severity: None
Priority: major
Owner: hubcap
Reporter: jburto2
Cc: 
Version: latest
Milestone: 
Status: closed
Resolution: fixed
Summary: Kernel module fails to build on SLES 12 (Linux 3.12.43-52.6)
Keywords: 

OrangeFS fails to build on the latest version of SLES 12. Make kmod fails with the following error. 

ec2-user@ofsnode-001:~/trunk> make kmod
  CC [M]  /home/ec2-user/trunk/src/kernel/linux-2.6/devpvfs2-req.o
/home/ec2-user/trunk/src/kernel/linux-2.6/devpvfs2-req.c: In function ‘pvfs2_devreq_aio_write’:
/home/ec2-user/trunk/src/kernel/linux-2.6/devpvfs2-req.c:577:37: error: dereferencing pointer to incomplete type
     return pvfs2_devreq_writev(kiocb->ki_filp, iov, count, &kiocb->ki_pos);
                                     ^
/home/ec2-user/trunk/src/kernel/linux-2.6/devpvfs2-req.c:577:66: error: dereferencing pointer to incomplete type
     return pvfs2_devreq_writev(kiocb->ki_filp, iov, count, &kiocb->ki_pos);
                                                                  ^
/home/ec2-user/trunk/src/kernel/linux-2.6/devpvfs2-req.c:578:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
scripts/Makefile.build:324: recipe for target '/home/ec2-user/trunk/src/kernel/linux-2.6/devpvfs2-req.o' failed
make[3]: *** [/home/ec2-user/trunk/src/kernel/linux-2.6/devpvfs2-req.o] Error 1
Makefile:1287: recipe for target '_module_/home/ec2-user/trunk/src/kernel/linux-2.6' failed
make[2]: *** [_module_/home/ec2-user/trunk/src/kernel/linux-2.6] Error 2
Makefile:99: recipe for target 'default' failed
make[1]: *** [default] Error 2
Makefile:860: recipe for target 'just_kmod' failed
make: *** [just_kmod] Error 2
ec2-user@ofsnode-001:~/trunk> uname -a
Linux ofsnode-001 3.12.43-52.6-default #1 SMP Wed May 20 12:44:39 UTC 2015 (fc0ceac) x86_64 x86_64 x86_64 GNU/Linux
ec2-user@ofsnode-001:~/trunk>
Ticket change
Time: 1436989318
Author: jburto2
Field: status

assigned

Ticket change
Time: 1436989318
Author: jburto2
Field: owner

hubcap

Ticket change
Time: 1436989318
Author: jburto2
Field: comment

OrangeFS was build on the following instance. Access it with the buildbot2.pem key

Jamess-MacBook-Pro:~ jburton$ '''/usr/bin/ssh -i ~/cuer1/buildbot2.pem ec2-user@130.127.193.51''' 

Ticket change
Time: 1447337984
Author: hubcap
Field: status

closed

Ticket change
Time: 1447337984
Author: hubcap
Field: resolution

fixed

Ticket change
Time: 1447337984
Author: hubcap
Field: comment

tested on:

$ cat /etc/SuSE-release
SUSE Linux Enterprise Desktop 12 (x86_64)
VERSION = 12
PATCHLEVEL = 0

$ uname -r
3.12.28-4-default
